# Generated by Django 4.2.17 on 2024-12-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=100)),
            ],
        ),
    ]
